### ISSUE TITLE
如何限制上传文件类型？

### ISSUE THREAD

**Issue by KRISACHAN** [xfworld/amazeuiUpload#4]
如何限制上传文件类型？需要我自己写逻辑么？

**Comment by xfworld** [comment]
不需要，只需要，你在初始化的时候把文件后缀配置进去就行；
不过提示信息，不够完善：） 有点挫，建议自己改善
<pre>
var AmazeuiUpload = function AmazeuiUpload(options) {
    this.url = options.url;
    this.downloadUrl = options.downloadUrl;
    this.maxFiles = options.maxFiles;
    this.maxFileSize = options.maxFileSize;
    this.multiThreading = options.multiThreading;
    this.fileType = options.fileType;
    this.useDefTemplate = options.useDefTemplate;
    this.knownType = options.knownType;
    this.selectMultiple = options.selectMultiple;
    this.selectType = options.selectType;
    this.dropType = options.dropType;
    this.pasteType = options.pasteType;
    this.context = options.context;
  }
</pre>
this.fileType 就是指的文件类型，是array，你可以自定义
